SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += ../../rtl/memory.sv

TOPLEVEL = memory
MODULE = test_memory

SIM_BUILD := ../../sim/memory/build
COCOTB_RESULTS_FILE := ../../sim/memory/results.xml

include $(shell cocotb-config --makefiles)/Makefile.sim